mirage/mirage-solo5

- solo5-bindings/Makefile
- solo5-bindings/alloc_pages_stubs.c
- solo5-bindings/clock_stubs.c
- solo5-bindings/cstruct_stubs.c
- solo5-bindings/main.c
- solo5-bindings/mm_stubs.c
- solo5-bindings/solo5_block_stubs.c
- solo5-bindings/solo5_console_stubs.c
- solo5-bindings/solo5_net_stubs.c
Ocaml-freestanding now has strict namespacing of libc headers to support
OCaml 4.03.0. Correctly include libc headers in Solo5 bindings. Also
update the Makefile to use stricter CFLAGS to catch errors.
> solo5-bindings: Sync with ocaml-freestanding changes

- mirage-solo5.opam
- solo5-bindings/Makefile
`CC?=cc` (history repeating), and adjust opam to allow building on non-linux systems (I expect this to work as well on OpenBSD/NetBSD/MacOSX)
> FreeBSD support

- solo5-bindings/Makefile
- solo5-bindings/atomic_stubs.c
This got missed in the refactoring of mirage-solo5 out of
mirage-platform. Required for building vchan unikernels in
mirage-skeleton.
> Re-add atomic_stubs.o

- solo5-bindings/Makefile
VAR?=value does not do what we thought it did.
> Use VAR=value to set implicit variables in Makefile

- .travis.yml
- lib/bindings/alloc_pages_stubs.c
- lib/bindings/main.c
- lib/bindings/mm_stubs.c
- lib/bindings/solo5_block_stubs.c
- lib/bindings/solo5_console_stubs.c
- lib/bindings/solo5_net_stubs.c
- lib/lifecycle.ml
- lib/mM.ml
- lib/main.ml
- lib/time.ml
General cleanup of the `mirage-solo5` code. Removes the unnecessary `Solo5: new bindings` message, cleans up formatting of other aborts/errors.
I've also cleaned up some of the stubs (removing dead/unused/debug code) and fixed all the OCaml warnings with the exception of
````
File "lib/time.ml", line 54, characters 2-17:
Warning 3: deprecated: module Lwt_pqueue
This module is an implementation detail of Lwt. See
http://ocsigen.org/lwt/dev/api/Lwt_pqueue
````
Could someone with more OCaml/Lwt chops than me give this a quick review and verify that I've not broken anything? @hannesm / @samoht perhaps?
> Cleanup and remove verbosity

- .travis.yml
- CHANGES.md
- opam
This is a point release needed because the name of the Io_page C stubs have changed: previously they had the prefix "caml_", which as @yallop points out is reserved for the OCaml compiler. The new convention is a prefix of "mirage_".
See [mirage/io-page#48]
Signed-off-by: David Scott <dave@recoil.org>
> Update CHANGES.md for 0.2.1

- opam
caml_alloc_pages -> mirage_alloc_pages
this is working fine with any io-page >= 2.0.0, but earlier versions require
caml_alloc_pages, which is no longer present.  since io-page and mirage-solo5
don't depend in any way on each other, adding a conflict here appeared like a
sensible solution.  evidence was thanks to our mirage-skeleton cron builder at
https://api.travis-ci.org/v3/job/317650589/log.txt
> in 0.2.1 (released 15th June 2017), the io-page stubs were renamed

- .travis.yml
- opam
- Restrict availability to OCaml 4.04.2 and newer as per mirage list
consensus
- Update build matrix
- Use Solo5/opam-solo5 to build against Solo5 master
~~- Switch Travis to container-based environment, now that a trusty one is available and we don't need sudo here~~
> opam, Travis: Switch to Solo5 master for development

- LICENSE.md
- lib/bindings/main.c
- lib/bindings/solo5_block_stubs.c
- lib/bindings/solo5_console_stubs.c
- lib/bindings/solo5_net_stubs.c
- lib/main.ml
- lib/oS.mli
- lib/oS.mlpack
- lib/solo5.ml
This adapts to Solo5 API changes in Solo5/solo5#245.
Additional refactoring in the OCaml/C stubs:
- Rename all Solo5-related C stubs into mirage_solo5_xxx namespace.
- Block and net stubs have been further refactored and "OCamlized".
This is intended to be reviewed in conjunction with PRs to mirage/mirage-{net,block,bootvar}-solo5 which depend on the C stub changes, I will open and link those shortly.
For ease of reviewing as diffs, I have not moved the refactored stubs into their respective packages; I plan to do this as a separate followup PR.
> Adapt to Solo5 API changes, refactor stubs

- .travis.yml
- opam
As of Solo5 0.4.0, the Solo5 OPAM packages have been renamed. This
updates mirage-solo5 to use the new package names, and conflict with the
old packages.
A post-installation message informing about the primary end-user change
("ukvm" target renamed to "hvt") has been added to "opam".
> Update for Solo5 0.4.0 renaming

- lib/bindings/solo5_block_stubs.c
- lib/bindings/solo5_net_stubs.c
See #37, this is not the full fix (requires changes in mirage-block-solo5, mirage-net-solo5).
I have intentionally changed the names of the C stubs, adding a suffix of `_2`, to prevent accidental linking with old versions of mirage-block-solo5, mirage-net-solo5.
> {block, net} stubs: Pass through Cstruct.buffer.off

- opam
This is mainly for Genode to ensure that the non-contiguous memory fix
is in place.
> opam: Bump ocaml-freestanding dependency to >= 0.4.1

- opam
- pkg/pkg.ml
this requires topkg 0.9.0 and opam2
> install mirage-solo5.pc to lib/pkconfig (instead of share/pkgconfig)

- _tags
- lib/main.ml
- lib/time.ml
- opam
- pkg/META
The goal of this PR is to remove usage of depreciated modules :
- `Lwt_sequence` is depreciated and is replaced with `Lwt_dllist`. This is actually the same library, packaged separately.
- `Lwt_pqueue` is depreciated and is replaced with `Binary_heap` (from bheap, as suggested [by the documentation](https://ocsigen.org/lwt/4.1.0/api/Lwt_pqueue). The bheap library allows to extract maximums, so the `compare` function was changed accordingly.
> Replace depreciated modules

- .travis.yml
- lib/bindings/main.c
- lib/bindings/solo5_block_stubs.c
- lib/bindings/solo5_net_stubs.c
- lib/main.ml
- lib/oS.mli
- opam
Update to Solo5 0.6.0 APIs, support multiple devices. This breaks downstream APIs.
Part of mirage/mirage#992.
> Update to new Solo5 "manifest"-style APIs

- lib/bindings/solo5_net_stubs.c
The block for `solo5_net_info` was allocated twice in case `solo5_net_acquire` was successful.
> Remove redundant allocation and fix whitespace

- .travis.yml
- lib/bindings/cstruct_stubs.c
- lib/bindings/solo5_net_stubs.c
In OCaml 4.10 the type of `String_val` changes from `char*` to `const char*`. `Bytes_val` should be used instead and it is compatible with older versions since mirage-solo5 requires at least OCaml 4.06 and `Bytes_val` was added in OCaml 4.06.
> Add support for OCaml 4.10

- .travis.yml
- lib/time.ml
- mirage-solo5.opam
Some API changes occured in `bheap` for the last release (https://github.com/ocaml/opam-repository/pull/17127).
It is recommended to use the latest version as it fixes the memory footprint and the API is more adapted to the use-case here. Namely it is no operating on minimums instead of maximums, (avoiding `invert_comparison`) and allow to create queues with initial size `0`.
It now requires a `dummy` value on creation, this is used internally to make sure no pointers are kept to unused values, that would prevent the GC from collecting them.
/cc @backtracking
> Adapt to bheap.2.0.0 changes

- lib/dune
- lib/main.ml
- lib/oS.mli
- lib/time.ml
- mirage-solo5.opam
the Time.Monotonic module was initially copied over from mirage-xen, and has not been used in any unikernels.
This PR reduces the exposed API of mirage-solo5, and streamlines the `Time` module with mirage-unix. Also, instead of hardcoding the number of seconds of a day, the `duration` library (which is dependency-free) is used.
Over time, MirageOS moved to use the `Time` module (`Mirage_time.S`) instead of backend-specific (unix, xen, soo5) interfaces and implementations. This is an API breaking change, but I could not find any unikernel which uses the removed Time.Monotonic interface. Once the dust in mirage-xen settles, I'll prepare PRs to streamline that implementation with mirage-solo5 one.
> remove Time.Monotonic submodule to unify mirage-solo5 with mirage-unix

- lib/time.ml
this was caused by cross-talk between #63 and #65
> fix compilation of time.ml: bind + to Int64.add only later

- lib/main.ml
- lib/time.ml
for future-proof, and make the code more explciit. re-binding + is not very intuitive.
> time: do not redefine +

- dune-project
- lib/bindings/Makefile
- lib/bindings/main.c
- lib/cflags.sh
- lib/dune
- lib/memory.ml
- lib/oS.ml
- lib/oS.mli
- lib/time.ml
- mirage-solo5.opam
This PR minimizes the difference between mirage-xen and mirage-solo5. To be finished and merged once mirage-xen 6.0.0 is released.
Changes included:
- remove unused Time.min_timeout
- adapt time.ml to mirage-xen's syntax
- use make to build libmirage-solo5_bindings.a instead of dune
- provide OS.Memory, the same interface as mirage/mirage-xen#26 (deprecating the old MM interface)
> Synchronise with mirage-xen

- .ocamlformat
- lib/bindings/clock_stubs.c
- lib/dune
The motivation is to avoid lots of conversions in mirage-clock just to retrieve
the current wall clock time. This is one part to solve
https://github.com/mirage/mirage-clock/issues/23
The unix_gettimeofday is still useful for the OCaml runtime system - which uses
it to initialize its RNG (the alternative is it being initialized with 0s which
is obviously worse) - that's why that symbol is kept as well.
> add caml_get_wall_clock -- similar to caml_get_monotonic_time

- lib/bindings/Makefile
- mirage-solo5.opam
Such a change has been trickled through other MirageOS3 cross-compilation
Makefiles as well. Also, use `opam var prefix`, not the deprecated
`opam config var prefix`. This also allows clean NixOS compilation.
> bindings Makefile: only invoke `opam var prefix` if opam is available

- lib/bindings/main.c
- lib/memory.ml
- lib/solo5_os.mli
As discussed previously with @dinosaure, with version v0.8.1 of ocaml-solo5, we can now have stats on the heap allocs & frees. This PR is identical to the PR on mirage-xen as we use solo5 in both cases. As @hannesm pointed out, I'm not sure how to add a constraint on a specific ocaml-solo5 version ?
> update with the new ocaml-solo5 interface

- lib/main.ml
Programs that uses `Lwt.pause ()` are potentially running slower than expected because they are sleeping between each iteration. 
The sleep time is chosen by the `Time.select_next` function, but it should be zero if there are paused continuations as they should be resumed as soon as possible, even if `solo5_yield` still has to be used to check for external events.
> Event loop: yield but don't sleep if there are paused tasks
